UPDATE Attraction SET rating = 4.0 WHERE name = 'SpierHead Winery';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Sperling Vineyards';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Rose House of Winery';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Sandhill Wines';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Quails'' Gate';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Ancient Hill Winery';
UPDATE Attraction SET rating = 4.5 WHERE name = 'CedarCreek Estate Winery';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Summerhill Pyramid Winery';
UPDATE Attraction SET rating = 4.5 WHERE name = 'The View Winery & Vineyard';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Tantalus Vineyards';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Rollingdale Winery';
UPDATE Attraction SET rating = 4.5 WHERE name = 'St Hubertus & Oak Bay Estate Winery';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Mt. Boucherie Estate Winery';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Vineyard Terrace Restaurant';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Beaumont Family Estate Winery';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Uncorked Wine Tours Kelowna';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Mission Hill Family Estate Winery';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Little Straw Vineyards';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Distinctly Kelowna Tours';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Volcanic Hills Estate Winery';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Waterfront Wines - Restaurant & Wine Bar';
UPDATE Attraction SET rating = 5.0 WHERE name = 'The Vibrant Vine';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Camelot Vineyards';
UPDATE Attraction SET rating = 3.5 WHERE name = 'Grizzli Winery';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Indigenous World Winery';
UPDATE Attraction SET rating = 4.5 WHERE name = 'The hatch';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Ex Nihilo Vineyards';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Experience Wine Tours';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Meadow Vista Honey Wines';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Kalala Organic Vineyards Ltd';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Off The Grid Organic Winery';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Frequency Winery - The Wine & Sound';
UPDATE Attraction SET rating = 4.5 WHERE name = 'McMillan Farms';
UPDATE Attraction SET rating = 3.5 WHERE name = 'Woodhaven Tree Farm & Tree Movers';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Kempf Orchards';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Okanagan Lavender and Herb Farm';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Arion Therapeutic Farm';
UPDATE Attraction SET rating = 4.9 WHERE name = 'Fairweather Farms Ltd';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Arlo''s Honey Farm';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Falcon Ridge Farms';
UPDATE Attraction SET rating = 4.8 WHERE name = 'Old Meadows Organic Farm & Market';
UPDATE Attraction SET rating = 3.5 WHERE name = 'Kelowna Free Graze Lamb';
UPDATE Attraction SET rating = 3.8 WHERE name = 'Eco Turf Farms';
UPDATE Attraction SET rating = 4.0 WHERE name = 'De Simone Farms Ltd';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Kangaroo Creek Farm';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Canyon Ridge Daylily Farm';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Hillcrest Farm Market & Cafe';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Lavender and Lace Floral Farm';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Mountain Valley Farm';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Sunshine Farms';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Mac Donnell Turf Farms';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Caldwell Heritage Farm';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Gellatly Nut Farm Regional Park';
UPDATE Attraction SET rating = 1.0 WHERE name = 'Stewart Bros Nurseries Ltd';
UPDATE Attraction SET rating = 4.7 WHERE name = 'Arndt Orchards';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Wise Earth Farm';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Cattail Creek Farms';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Kelowna City Park';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Waterfront Park';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Knox Mountain Park';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Stillingfleet Park';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Boyce -Gyro Beach Park';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Mission Creek Regional Park';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Kusagai Gardens';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Osprey Park';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Cameron Park';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Sonora Park';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Parkinson Recreation Park';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Ben Lee Park';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Munson Pond Park';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Lombardy Park';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Rotary Beach Park';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Jack Robertson Memorial Park';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Millbridge Park';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Rutland Centennial Park';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Kinsmen Park';
UPDATE Attraction SET rating = 3.5 WHERE name = 'Strathcona Park';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Chichester Wetland Park';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Landmark Cinemas 8 Xtreme West Kelowna';
UPDATE Attraction SET rating = 3.9 WHERE name = 'Landmark Cinemas Grand 10 Kelowna';
UPDATE Attraction SET rating = 3.7 WHERE name = 'Blue Gator Bar & Grill';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Rotary Centre for the Arts';
UPDATE Attraction SET rating = 4.4 WHERE name = 'Kelowna Community Theatre';
UPDATE Attraction SET rating = 4.1 WHERE name = 'The Grateful Fed Pub & Restaurant';
UPDATE Attraction SET rating = 3.6 WHERE name = 'Lake City Casino Kelowna';
UPDATE Attraction SET rating = 3.8 WHERE name = 'Dakoda''s Sports Bar & Grill';
UPDATE Attraction SET rating = 4.6 WHERE name = 'Landmark Cinemas Encore West Kelowna';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Festivals Kelowna';
UPDATE Attraction SET rating = 4.1 WHERE name = 'Okanagan Express Entertainment Limousine Services';
UPDATE Attraction SET rating = 2.0 WHERE name = 'Kelowna Dragon Boat Club';
UPDATE Attraction SET rating = 4.1 WHERE name = 'Chances Kelowna';
UPDATE Attraction SET rating = 4.6 WHERE name = 'Kelowna Actors Studio';
UPDATE Attraction SET rating = 4.4 WHERE name = 'Tourism Kelowna';
UPDATE Attraction SET rating = 4.0 WHERE name = 'LIQUID ZOO';
UPDATE Attraction SET rating = 3.5 WHERE name = 'Rose''s Waterfront Pub';
UPDATE Attraction SET rating = 3.4 WHERE name = 'Heights Nightclub';
UPDATE Attraction SET rating = 4.5 WHERE name = 'HQ49';
UPDATE Attraction SET rating = 3.1 WHERE name = 'Gateway Casinos & Entertainment Ltd Corporate Office';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Yamas Taverna';
UPDATE Attraction SET rating = 4.3 WHERE name = 'Prospera Place';
UPDATE Attraction SET rating = 4.8 WHERE name = 'Wine & Art Piano Bar';
UPDATE Attraction SET rating = 3.5 WHERE name = 'Rusty''s Steakhouse';
UPDATE Attraction SET rating = 4.5 WHERE name = 'OK Corral & Cabaret';
UPDATE Attraction SET rating = 4.5 WHERE name = 'EXIT Kelowna';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Ballet Kelowna';
UPDATE Attraction SET rating = 4.7 WHERE name = 'BNA Brewing Co';
UPDATE Attraction SET rating = 3.9 WHERE name = 'Scandia Golf & Games';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Airwaves Music DJs';
UPDATE Attraction SET rating = 4.7 WHERE name = 'Avalon Event Rentals';
UPDATE Attraction SET rating = 4.8 WHERE name = 'Myra Canyon Adventure Park';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Kelowna Magician & Entertainer Leif David - Ali K. Zam Productions';
UPDATE Attraction SET rating = 4.4 WHERE name = 'Play It Again Sports';
UPDATE Attraction SET rating = 4.9 WHERE name = 'Deschners Danceforce';
UPDATE Attraction SET rating = 3.9 WHERE name = 'Sunset Ranch Golf & Country Club';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Bowie''s Marketing & Entrtn';
UPDATE Attraction SET rating = 4.4 WHERE name = 'Beyond The Crux Climbing Gym Inc.';
UPDATE Attraction SET rating = 3.5 WHERE name = 'Planet Lazer';
UPDATE Attraction SET rating = 3.8 WHERE name = 'Energyplex Family Recreation Centre Kelowna';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Safari Ridge Adventure Park';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Parkinson Recreation Park';
UPDATE Attraction SET rating = 4.4 WHERE name = 'Kelowna Family YMCA';
UPDATE Attraction SET rating = 3.9 WHERE name = 'H2O Adventure + Fitness Centre';
UPDATE Attraction SET rating = 4.4 WHERE name = 'Kelowna Pool Tables & Games Room Furniture';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Father Pandosy Mission';
UPDATE Attraction SET rating = 4.3 WHERE name = 'Guisachan House';
UPDATE Attraction SET rating = 4.9 WHERE name = 'Myra Trestles';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Benvoulin Heritage Church';
UPDATE Attraction SET rating = 4.7 WHERE name = 'The Laurel Building';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Knox Mountain';
UPDATE Attraction SET rating = 4.8 WHERE name = 'Mill Creek Regional Park';
UPDATE Attraction SET rating = 3.9 WHERE name = 'Stephens Coyote Ridge Regional Park';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Bear Creek Provincial Park';
UPDATE Attraction SET rating = 4.5 WHERE name = 'Paul''s Tomb';
UPDATE Attraction SET rating = 4.0 WHERE name = 'Cedar Mountain Regional Park';
UPDATE Attraction SET rating = 4.3 WHERE name = 'Rose Valley Regional Park';
UPDATE Attraction SET rating = 4.6 WHERE name = 'Kalamoir Park';
UPDATE Attraction SET rating = 4.3 WHERE name = 'Scenic Canyon Regional Park';
UPDATE Attraction SET rating = 5.0 WHERE name = 'Wrinkly Face Provicinal Park';
